// lib/chatbot/intentData.js

export const INTENT_DATASET = [
  ["halo", "greeting"],
  ["hai", "greeting"],
  ["selamat pagi", "greeting"],
  ["permisi", "greeting"],

  ["ada voltes v", "product_discovery"],
  ["cari voltes v", "product_discovery"],

  ["rekomendasi voltron untuk pajangan", "recommendation"],
  ["robot yang cocok untuk display", "recommendation"],

  ["ini original bandai", "product_detail"],
  ["ukuran produk ini berapa", "product_detail"],

  ["harga produk ini berapa", "price_promo"],
  ["berapa harganya", "price_promo"],

  ["ini ready stock", "stock_availability"],
  ["masih ada ga", "stock_availability"],

  ["ongkir ke jakarta berapa", "shipping_transaction"],
  ["ongkir ke tangerang berapa", "shipping_transaction"],
  ["metode pembayaran apa saja", "shipping_transaction"],
  ["pembayarannya bisa pakai apa saja", "shipping_transaction"],
  ["bisa bayar pakai qris", "shipping_transaction"],
  ["bisa transfer bank apa saja", "shipping_transaction"],
  ["cara checkout gimana", "shipping_transaction"],
  ["cara order di sini gimana", "shipping_transaction"],
  ["cara beli produk ini gimana", "shipping_transaction"],
  ["cara membeli produk ini gimana", "shipping_transaction"],
  ["bagaimana cara membeli produk", "shipping_transaction"],
  ["proses pembelian gimana", "shipping_transaction"],
  ["mau beli produk ini gimana", "shipping_transaction"],
  ["estimasi pengiriman berapa hari", "shipping_transaction"],
  ["berapa lama pengiriman", "shipping_transaction"],
  ["bisa cod atau tidak", "shipping_transaction"],
  ["pakai asuransi pengiriman bisa", "shipping_transaction"],

  ["pengiriman dari mana", "shipping_origin"],
  ["dikirim dari mana", "shipping_origin"],

  ["barang rusak bisa retur", "return_product"],
  ["kalau mau refund gimana", "return_product"],

  ["cek status pesanan", "transaction_status"],
  ["status transaksi saya", "transaction_status"],
  ["cek status order saya", "transaction_status"],
  ["pesanan saya sudah diproses belum", "transaction_status"],
  ["status pembelian saya gimana", "transaction_status"],
  ["cek order id", "transaction_status"],

  ["cek resi saya", "shipment_tracking"],
  ["lacak paket", "shipment_tracking"],
  ["paket saya sudah sampai mana", "shipment_tracking"],
  ["cek nomor resi", "shipment_tracking"],

  ["bandingkan voltes v dengan grendizer", "compare"],
  ["voltron vs megazord", "compare"],
  ["mana lebih bagus voltes v atau grendizer", "compare"],
  ["apa bedanya produk a dan produk b", "compare"],
];

export const INTENT_STOPWORDS = new Set([
  "yang",
  "yg",
  "nya",
  "apa",
  "mana",
  "ini",
  "itu",
  "ga",
  "gak",
  "nggak",
  "kah",
  "dong",
  "deh",
  "ya",
  "pak",
  "bu",
  "kak",
  "min",
  "admin",
  "tolong",
  "minta",
  "produk",
  "barang",
  "robot",
  "mainan",
]);

export const INTENT_KEYWORDS = {
  greeting: [
    "halo",
    "hallo",
    "hai",
    "hi",
    "hello",
    "pagi",
    "siang",
    "sore",
    "malam",
    "permisi",
  ],

  product_discovery: [
    "cari",
    "list",
    "pilihan",
    "koleksi",
    "dicari",
    "series",
    "seri",
  ],

  product_detail: [
    "original",
    "ori",
    "ukuran",
    "size",
    "dimensi",
    "berat",
    "weight",
    "bahan",
    "material",
    "diecast",
    "limited",
    "edisi",
    "versi",
    "spesifikasi",
    "isi",
    "box",
    "misb",
    "kondisi",
  ],

  price_promo: [
    "harga",
    "murah",
    "mahal",
    "termurah",
    "termahal",
    "diskon",
    "promo",
    "sale",
    "cashback",
    "bundle",
    "hemat",
    "dibawah",
    "di bawah",
    "diatas",
    "di atas",
    "lebih dari",
    "kurang dari",
    "antara",
    "sampai",
    "jt",
    "juta",
    "rb",
    "ribu",
  ],

  stock_availability: [
    "stok",
    "stock",
    "ready",
    "ready stock",
    "tersedia",
    "habis",
    "restock",
    "preorder",
    "po",
    "inden",
    "sisa",
  ],

  shipping_transaction: [
    "ongkir",
    "kirim",
    "pengiriman",
    "ekspedisi",
    "cod",
    "qris",
    "transfer",
    "bayar",
    "checkout",
    "cara checkout",
    "cara beli",
    "cara membeli",
    "cara order",
    "cara pesan",
    "membeli produk",
    "proses pembelian",
    "mau beli",
    "how to buy",
    "pesan",
    "ambil",
    "pickup",
    "alamat",
    "pembayaran",
    "metode pembayaran",
    "gopay",
    "bank",
    "visa",
    "kartu kredit",
    "asuransi",
    "proteksi",
    "bayar di tempat",
    "cash on delivery",
    "estimasi sampai",
    "estimasi pengiriman",
    "berapa hari",
    "kapan sampai",
    "lama kirim",
    "lama pengiriman",
    "estimasi",
  ],

  shipping_origin: [
    "dari mana",
    "dikirim dari",
    "asal pengiriman",
    "lokasi pengiriman",
    "gudang",
    "warehouse",
    "origin",
    "kirim dari",
    "lokasi toko",
    "lokasi offline",
    "toko offline",
  ],

  return_product: [
    "retur",
    "pengembalian barang",
    "return",
    "refund",
    "komplain",
    "complain",
    "rusak",
    "cacat",
    "part kurang",
    "kurang part",
    "tidak lengkap",
    "box penyok",
    "penyok",
    "salah kirim",
    "tidak sesuai deskripsi",
    "pengembalian uang",
    "uang kembali",
    "dana kembali",
  ],

  recommendation: [
    "rekomendasi",
    "recommended",
    "rekomen",
    "terbaik",
    "bagus",
    "cocok",
    "worth it",
    "untuk pajangan",
    "buat pajangan",
    "display",
    "koleksi",
    "untuk koleksi",
    "hadiah",
    "alasan",
    "alasannya",
    "kenapa",
    "pajangan",
    "budget",
  ],

  compare: [
    "bandingkan",
    "compare",
    "versus",
    "vs",
    "apa bedanya",
    "bedanya",
    "perbedaan",
    "beda dengan",
    "lebih bagus",
    "lebih baik",
    "bagusan",
    "pilih yang mana",
    "mana yang cocok",
  ],

  transaction_status: [
    "status transaksi",
    "status pesanan",
    "status order",
    "status orderan",
    "status pembelian",
    "order id",
    "cek order",
    "cek pesanan",
    "cek transaksi",
    "cek pembelian",
    "nomor pesanan",
    "no pesanan",
    "id pesanan",
    "pesanan saya",
    "order saya",
    "diproses",
  ],

  shipment_tracking: [
    "cek resi",
    "nomor resi",
    "lacak paket",
    "tracking paket",
    "paket saya sudah sampai mana",
    "status pengiriman paket",
  ],
};
